apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: alpine:latest
        command: ["echo",  "Matthew"]
      restartPolicy: Never
  backoffLimit: 4
